matrix:
  include:
    - os: macos
      sudo: required
      language: node_js
      node_js: 16
      python: 3.7
      osx_image: xcode11
      env:
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
      script:
        - npm install
        - npm test
        - python build.py

    - os: linux
      dist: focal
      sudo: required
      language: node_js
      node_js: 16
      python: 3.7
      env:
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
      script:
        - sudo apt install build-essential -y
        - npm install
        - npm test
        - python build.py

    - os: linux
      dist: bionic
      sudo: required
      language: node_js
      node_js: 16
      python: 3.7
      env:
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
      script:
        - sudo apt install build-essential -y
        - npm install
        - npm test
        - python build.py

    - os: linux
      dist: xenial
      sudo: required
      language: node_js
      node_js: 16
      python: 3.7
      env:
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
      script:
        - sudo apt install build-essential -y
        - npm install
        - npm test
        - python build.py

addons:
  ssh_known_hosts: web.sourceforge.net


after_success:
  - openssl aes-256-cbc -K $encrypted_906d16ae5679_key -iv $encrypted_906d16ae5679_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - scp -i /tmp/deploy_rsa dist/ScanCode*.tar.gz aboutcode-rel@web.sourceforge.net:/home/frs/project/aboutcode-manager/builds/
