version: '{build}'

image: Visual Studio 2013

platform:
  - x64

install:
  - ps: Install-Product node 6 x64
  - node --version
  - npm --version

build_script:
  - npm install
  - python build.py
  - openssl version
  - ssh -V
  - scp -v

test: off
